---
dependency:
  name: galaxy
driver:
  name: delegated
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8 molecule/tests
platforms:
  - name: instance
    image_owner: ${AWS_ACCOUNT_ID:-895523100917}
    image_name: "HMPPS Base CentOS master *"
    instance_type: t2.micro
    vpc_subnet_id: ${VPC_SUBNET_ID:-subnet-043763902fc8ac91c}
    instance_tags:
      destroy: true
      Created_by: molecule
      Name: hmpps-ansible-samba-role
provisioner:
  name: ansible
  playbooks:
    create: create.yml
    converge: converge.yml
    destroy: destroy.yml
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  directory: ../tests
  options:
    v: true
    sudo: true
  lint:
    name: flake8
